### ISSUE TITLE
saveEventsFile - warning

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_BIDS#56] opened 2020-07-27 19:56 UTC
1. Warning
It seems to be passing this warning when there's nan. But I think I still have nans - as early Xmas decoration in my response collection array, somehow. Thus I have 13 (number of button pressed) error messages like this:
```
Warning: Missing some target data for this event. 
> In saveEventsFile>checkExtracolumns (line 240)
  In saveEventsFile>checklLogFile (line 166)
  In saveEventsFile (line 84)
  In fMRIMainExperiment (line 229) 
           onset: 199.7325
      trial_type: 'response'
        duration: 0
        key_name: 'space'
         pressed: 1
          fileID: []
    extraColumns: []
          target: NaN
```

2. It does not separate the time of the date in the saving name:
`sub-001_ses-001_task-RhythmCategFT_run-001_events_date-202007272044.tsv
`previously it was:
`sub-001_ses-001_task-RhythmCategFT_run-001_events_date-20200727_2044.tsv
`
Previous version was slightly easier for a human to read.

**Comment by Remi-Gau** [comment] 2020-07-28 06:09
**On point 2.**

Yes. I know but the problem is that I want to have a function in there to easily convert from source data to true raw bids (there is one actually :smile: ).

The true raw data cannot have time stamps in the name. This is not allowed in the bids specs. But I added it there to prevent overwriting files. Just in case. I am paranoid about keeping even cancelled runs during my experiments.
So we need a way to parse the filenam to easily locate the date suffix and remove it when converting to real true bids. 

But the `-` and the `_` are already taken in the bids filenaming. So I decide to concatenate hours and minutes with the date.

Harder to parse for humans. Though. But I am open to suggestions.


**About warning.**

It says that the field "target" contains one or more nans. And the output seems to be consistent with that.
Or am I missing something?

**Comment by Remi-Gau** [comment] 2020-08-04 17:15
Will close thisn one for now

**Closed by Remi-Gau** 2020-08-04 17:15 UTC
